travis:
  secure:
    BINSTAR_TOKEN: tq5Xp8DTJcUcfJrEnzg8MM9UQJY5eoFfNMRD56Ba6Nrba1SxnNcDj8m0nIioah7+2tp2+GlJgbiGjcoALSuqUEakOsJEyiQAcZ81L6ajtxV+Qlh4STQkJScjQhzTWqNCK7cHF6ALrdsPUGENn2w8lZPBTn1R0rP6MBL9tk3GfOFxaQXTEVV55sAJeKx0dV7SKb2jFpqUSG/DflSEEcx1MaYgnJ8uhPe/oad0wVG2F6+JeNG58GMxDXi67XSskoQZVoqLES+39ClwEISKB1q6r66c4X1YREwdefjTPLi+WRNEqGmCCxNiBvCYGGPngskuXCSN50xUeZl6ZX41If14r3k2Fnsb7kPUIX6xptMnLGJ7Vn/DPbA4DKDjbRhYTZ03Z98SCjz660lJ4qV8UfOWVd5pWVnSSi6LQs/Tg5onA5EwEtU5yfpiQ2jC4wc9XcIq0krRZsqZpJD78iMMbBfYKe71gM5l5JLK47wrT0+YK496WDAmTahHJqLbmw0v/78r208xRfjO2TzXcA1Tc4DB3dnMmewtF+H5an35ZDsjZmbr3YxautEsn4tB+lDIcYzfXXUEI7Mm1AmNHhJiB2fN9tO6Ad5mhTVGALbWOhDjgQfZbkmsQHTan622VzXMeAkF2Zu+AyP811Ks9grrGdGvg8Dgak+9LrvfizB1rHmkP78=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
